- hosts: localhost
  connection: local
  vars:
    nix_channel: https://nixos.org/channels/nixos-23.11
    source_key: "./.ssh/id_rsa"

  tasks:
    - name: Detect operating system
      set_fact:
        is_arch: "{{ ansible_distribution == 'Archlinux' }}"

    - name: Run core tasks (require sudo)
      become: true
      import_tasks: tasks/core.yml

    - name: Install and configure Nix
      import_tasks: tasks/nix.yml

    - name: Configure SSH
      import_tasks: tasks/ssh.yml

    - name: Provide next steps for Nix usage
      debug:
        msg: |
            Nix has been installed, but you need to start a new shell session for it to take effect.
            Please do one of the following:
            1. Log out and log back in
            2. Start a new terminal session
            3. Run 'exec $SHELL' in your current terminal
            After that, you should be able to use Nix commands.
            Next step 'git clone git@github.com:trynn-tech/dotfiles.git'
