- hosts: localhost
  vars:
    ansible_user_id: trynn
    nix_channel: https://nixos.org/channels/nixos-23.11
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ ansible_env.HOME }}/.ssh/id_rsa"

  become: True
  become_method: sudo

  pre_tasks:
    - name: Detect operating system
      set_fact:
        is_arch: "{{ ansible_distribution == 'Archlinux' }}"

  tasks:
    - import_tasks: tasks/core.yml
    - import_tasks: tasks/nix.yml
    - import_tasks: tasks/ssh.yml
