- hosts: localhost
  connection: local
  vars:
    nix_channel: https://nixos.org/channels/nixos-23.11
    source_key: "./.ssh/id_rsa"

  tasks:
    - name: Detect operating system
      set_fact:
        is_arch: "{{ ansible_distribution == 'Archlinux' }}"

    - name: Run core tasks (require sudo)
      become: true
      import_tasks: tasks/core.yml

    - name: Install and configure Nix
      import_tasks: tasks/nix.yml

    # Uncomment the following line when ready to include SSH tasks
    # - name: Configure SSH
    #   import_tasks: tasks/ssh.yml
