- name: Install essential packages (Arch)
  pacman:
    name: 
      - curl
      - sudo
      - openssh
      - base-devel
      - expect
    update_cache: yes
    state: present
  when: is_arch

- name: Allow user to run sudo without password
  lineinfile:
    path: /etc/sudoers
    line: '{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  become: yes

